services:
  postgres:
    image: postgres:17.2
    restart: "no"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: test-task
      POSTGRES_PASSWORD: test-task
      POSTGRES_DB: test-task
  idf-test-task:
    image: pr1ntle/idf-test-task:latest
    build: .
    restart: "no"
    ports:
      - "8080:8080"
    environment:
     POSTGRES_HOST: postgres:5432
     POSTGRES_USERNAME: test-task
     POSTGRES_PASSWORD: test-task
     POSTGRES_DB_NAME: test-task
    env_file:
      - .env
    depends_on:
      - postgres
volumes:
  postgres_data:
