CREATE TABLE limits (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   amount_usd numeric(19, 2) NOT NULL,
   date_set date NOT NULL,
   expense_category VARCHAR(20) NOT NULL,
   CONSTRAINT limits_pkey PRIMARY KEY (id)
);

CREATE TABLE transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   account_from INTEGER NOT NULL,
   account_to INTEGER NOT NULL,
   currency_shortname VARCHAR(255) NOT NULL,
   date_time TIMESTAMP WITH TIME ZONE NOT NULL,
   expense_category VARCHAR(20) NOT NULL,
   limit_exceeded BOOLEAN NOT NULL,
   sum numeric(19, 2) NOT NULL,
   sum_usd numeric(19, 2) NOT NULL,
   exchange_rate_id INTEGER NOT NULL,
   limit_id INTEGER,
   CONSTRAINT transactions_pkey PRIMARY KEY (id)
);

CREATE TABLE exchange_rates (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   currency_pair VARCHAR(15) NOT NULL,
   date date NOT NULL,
   rate numeric(19, 6) NOT NULL,
   CONSTRAINT exchange_rates_pkey PRIMARY KEY (id)
);

ALTER TABLE transactions ADD CONSTRAINT fk34ph3qr52tp7rlpxqr793h0a9 FOREIGN KEY (limit_id) REFERENCES limits (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE transactions ADD CONSTRAINT fkg0jclfy7bmbi5yg9m0gkvbqy7 FOREIGN KEY (exchange_rate_id) REFERENCES exchange_rates (id) ON UPDATE NO ACTION ON DELETE NO ACTION;